Order.cs tar en DateTime som parameter, detta lagras på db, under acc…
NicTheStudent/software-engineering-project pull request #24
Opened 2019-05-22 14:34 UTC by osgro19

…ount finns en knapp för gamla beställningar, ny page OldOrders, DatabaseFacade har en ny funk som sorterar orders efter dagens datum

2019-05-22 14:38 UTC, osgro19 commented
Vill man testa så att gamla ordrar visas under Mitt Konto>Gamla Beställningar måste man populera db med ordrar där timeSold är innan dagens datum och tid för era konton. Ni kan se hur jag har gjort det i PopulateDB.

2019-05-22 20:01 UTC, FreLindberg requested changes

2019-05-22 20:01 UTC, FreLindberg commented on REKO/REKO/OldOrders.xaml.cs
> +            MainListView.ItemsSource = null;
Don't need to set to null here.

2019-05-22 20:01 UTC, FreLindberg commented on REKO/REKO/classes/DatabaseFacade.cs
> +        public List<Order> GetOrdersFilteredOldAndUser(User user)
You are not filtering users, you are filtering ON users. Why is "User" included in the name of the function?

2019-05-22 20:01 UTC, FreLindberg commented on REKO/REKO/classes/PopulateDB.cs
> +                orderList.Add(new Order(userList[0], offerList[0], 1, 1, offerList[0].Seller.RekoRing.nextMeetup));
Here you are setting the timeSold to the START of the meetup of the REKO-ring. Won't this result in a order becoming inactive during the meetup? (saying the meetup lasts between 18:00-20:00).

2019-05-22 20:31 UTC, HBroman commented on REKO/REKO/OldOrders.xaml.cs
> +            MainListView.ItemsSource = null;
Faktum är att det är meningslöst att overridea OnApearing här, det är bara relevant i tabbarna. Varje gång den här sidan skapas görs en ny instans av den, så att sätta itemsource i konstruktorn räcker.

2019-05-23 07:10 UTC, osgro19 commented on REKO/REKO/classes/DatabaseFacade.cs
> +        public List<Order> GetOrdersFilteredOldAndUser(User user)
Ja, jag filtrerar Orders på User och DateTime för att få fram de Orders som stämmer överens med de villkor som finns, nämligen datum/tid och user. Vad tänkte du var problemet?

2019-05-23 07:11 UTC, osgro19 commented on REKO/REKO/classes/PopulateDB.cs
> +                orderList.Add(new Order(userList[0], offerList[0], 1, 1, offerList[0].Seller.RekoRing.nextMeetup));
Tycker att det är en sådan liten detalj och inte kommer ge mycket värde att implementera det. Antingen kan vi anta att alla tar 2 timmar eller så får en variabel finnas med i RekoRing som säger hur länge det håller på. Oavsett tycker jag att det är onödigt arbete.

2019-05-23 07:16 UTC, osgro19 commented on REKO/REKO/OldOrders.xaml.cs
> +            MainListView.ItemsSource = null;
Detta är löst nu.

2019-05-23 14:12 UTC, FreLindberg commented on REKO/REKO/classes/DatabaseFacade.cs
> +        public List<Order> GetOrdersFilteredOldAndUser(User user)
Namnet på funktionen är förvirrande i jämförelse till vad den gör. Men det är bara en liten grej, du kan behålla det om du tycker att det är bra.

2019-05-23 14:13 UTC, FreLindberg commented on REKO/REKO/classes/PopulateDB.cs
> +                orderList.Add(new Order(userList[0], offerList[0], 1, 1, offerList[0].Seller.RekoRing.nextMeetup));
Det suger ju att inte kunna se vad man har beställt medans man går runt och hämtar sina saker. Tycker personligen inte att ett erbjudande ska bli inaktivt för än veckans reko-ring faktiskt är över.

2019-05-23 16:38 UTC, FreLindberg approved these changes
Du får välja om du vill ändra på de sakerna jag har lagt kommentarer på själv. Annars ser det bra ut. Glöm självklart inte att fixa så att du kan merga bara.

2019-05-23 18:03 UTC, osgro19 commented on REKO/REKO/classes/DatabaseFacade.cs
> +        public List<Order> GetOrdersFilteredOldAndUser(User user)
Jaha, då förstår jag. Själv tycker jag den är bra men om du gärna vill byta den så är det lugnt för min del.

2019-05-23 18:08 UTC, osgro19 commented on REKO/REKO/classes/PopulateDB.cs
> +                orderList.Add(new Order(userList[0], offerList[0], 1, 1, offerList[0].Seller.RekoRing.nextMeetup));
Det verkar som att REKO-ringar håller på i max en timma så jag kan se till att de inte försvinner förrän två timmar efteråt eller nåt.

2019-05-23 20:00 UTC, FreLindberg approved these changes
Fix the merge conflict first, and then you can merge.

2019-05-23 20:59 UTC, merged